### ISSUE TITLE
在 jekyll themes 的页面信息部分失效

### ISSUE THREAD

**Issue by mikelyou** [wu-kan/wu-kan.github.io#10]
你好，我是从[jekyll themes](http://jekyllthemes.org/themes/wu-kan/) 看到这个漂亮的主题的，非常喜欢！
我注意到 jekyll themes 那边的页面上，demo的网址和效果图全都失效了，也许需要更新一下呢。:smile:

**Comment by wu-kan** [comment]
好的 我已经给 [mattvh/jekyllthemes](https://github.com/mattvh/jekyllthemes) 交了一个 [PR](https://github.com/mattvh/jekyllthemes/pull/723) 接下来等待更新即可

**Comment by mikelyou** [comment]
好滴 😄 🎉  原来也是github项目，没有注意到哈哈
