### ISSUE TITLE
关于同步仓库的问题

### ISSUE THREAD

**Issue by GGXXLL** [wu-kan/wu-kan.github.io#12]
首先感谢wu-kan大佬！
很喜欢大佬的博客，但是有个问题，大佬的知识结晶已经很多了（帖子和图片）， 仓库好大啊
fork之后，clone到本地或者之后同步大佬的仓库，速度很慢
不知道大佬有没有好的解决方案

**Comment by AmachiInori** [comment]
git拉取时设置过滤关键字，所有的图片都不拉取。

或者选择性地下载（需要维护目录结构）
```
/_posts/1999-06-21-*.md （共5个）
直接位于根目录下的所有文件 （共7个）
```

**Comment by GGXXLL** [comment]
好的，我试试，嘿嘿👍🏻

**Comment by wu-kan** [comment]
可以试试用 svn 代替 git，从而只下载这个仓库的部分文件。参照这个 [issue](https://github.com/wu-kan/wu-kan.github.io/issues/7)
