### ISSUE TITLE
对KaTeX过长公式渲染超出页面的修正

### ISSUE THREAD

**Issue by AmachiInori** [wu-kan/wu-kan.github.io#13]
小问题，今天在迁移博文的时候发现公式过长时在移动端显示不全，然后随手测试了一下，发现桌面端也有同样的问题。
修正还是简单的，对公式加一个底端滚动条。
KaTeX公式渲染的class名称是`katex-display`，加一条CSS
```HTML
<style>
  .katex-display {
    min-height: 100%;
    width: 100%;
    overflow-x: auto;
    overflow-y: hidden;
  }
  @media (max-aspect-ratio: 2400/1850) {
    .katex-display::-webkit-scrollbar {
      display: none; /*在移动端不显示横向滚动条*/
    }
  }
</style>
```
推荐放到`page.katex.append`键里

**Comment by wu-kan** [comment]
这么做似乎会导致公式最底下几个像素被吞掉，如图

```markdown
$$
\oint_{V}\triangledown Q dV=\iint_{\partial V}Q\cdot\vec{n}dS
$$
```

![image](https://user-images.githubusercontent.com/44857941/92319663-66703880-f04d-11ea-9d4b-f00b986d687d.png)

![image](https://user-images.githubusercontent.com/44857941/92319684-93245000-f04d-11ea-81f2-82f723c753e5.png)

考虑到超长公式本身可以在写的时候手动分行（通过加`\\`），长公式显示不全的问题其实是可以手动规避的（毕竟使用 tex 的时候本身已经对排版有比较高要求），我觉得这个问题还是可以先搁置一下 :sweat:

**Comment by AmachiInori** [comment]
另外一个方案是自动换行..
我个人觉得这个问题在移动端还是挺严重的，毕竟手动换行不能兼顾多种浏览器分辨率
```html
<style>
  .katex-display>.katex {
    white-space: normal;
  }
</style>
```
总之我先close掉了

**Comment by MURENzz** [comment]
> 另外一个方案是自动换行.. 我个人觉得这个问题在移动端还是挺严重的，毕竟手动换行不能兼顾多种浏览器分辨率
> 
> <style>
>   .katex-display>.katex {
>     white-space: normal;
>   }
> </style>
> 总之我先close掉了

确实很严重，网页端配置的好好的，打开移动端天塌了，手动不可能同时适配两者的。。

**Comment by wu-kan** [comment]
> > 另外一个方案是自动换行.. 我个人觉得这个问题在移动端还是挺严重的，毕竟手动换行不能兼顾多种浏览器分辨率
> > 
> > <style>
> >   .katex-display>.katex {
> >     white-space: normal;
> >   }
> > </style>
> > 总之我先close掉了
> 
> 确实很严重，网页端配置的好好的，打开移动端天塌了，手动不可能同时适配两者的。。

所以被引用的自动换行的方法可以解决吗？目前应该是有用这个自动换行的
