### ISSUE TITLE
文章的背景透明度怎么调整

### ISSUE THREAD

**Issue by Yecgaa1** [wu-kan/wu-kan.github.io#15]
![xutongxin1 github io__posts_2020-12-17-xtx%E7%AC%AC15%E5%91%A8%E5%B7%A5%E7%A8%8B%E5%BC%80%E5%8F%91%E6%97%A5%E5%BF%97_(computer)](https://user-images.githubusercontent.com/38446391/102740452-cc799500-438a-11eb-8b0d-b4971a922f69.png)
希望可以给我一些魔改的思路
本人并不会css和js，但是比较喜欢改代码试出自己想要的效果
谢谢

**Comment by wu-kan** [comment]
在 [`_config.yml`](https://github.com/wu-kan/wu-kan.github.io/blob/master/_config.yml) 中找到 `background-color: ` 这一设置项（542行左右），目前我设定的值是 `rgba(255,255,255,.9);`，即 90% 不透明度的白色。

**Comment by Yecgaa1** [comment]
确实很有效
我还有一个问题，能不能做到说让图片可以随页面滚动，但同时若图片滚到最下方图片不再跟随滚动而内容继续滚动呢
我尝试着把background-attachment改为了scroll或local，同时background-size为cover时，我的背景图会出现一定的内容压缩（如果文章长而图片主题比较大时，虽然说是等比例缩放但是效果不太好），改background-size为contain时下半页面出现图片缺失
希望可以给予我一些建议，麻烦你了

**Comment by wu-kan** [comment]
> 确实很有效
> 我还有一个问题，能不能做到说让图片可以随页面滚动，但同时若图片滚到最下方图片不再跟随滚动而内容继续滚动呢
> 我尝试着把background-attachment改为了scroll或local，同时background-size为cover时，我的背景图会出现一定的内容压缩（如果文章长而图片主体人物啊比较宽时，虽然说是等比例缩放但是效果不太好），改background-size为contain时下半页面出现图片缺失
> 希望可以给予我一些建议，麻烦你了

这个我不清楚啦hh，我也不是学前端的

**Comment by Yecgaa1** [comment]
> > 确实很有效
> > 我还有一个问题，能不能做到说让图片可以随页面滚动，但同时若图片滚到最下方图片不再跟随滚动而内容继续滚动呢
> > 我尝试着把background-attachment改为了scroll或local，同时background-size为cover时，我的背景图会出现一定的内容压缩（如果文章长而图片主体人物啊比较宽时，虽然说是等比例缩放但是效果不太好），改background-size为contain时下半页面出现图片缺失
> > 希望可以给予我一些建议，麻烦你了
> 
> 这个我不清楚啦hh，我也不是学前端的

没关系，因为我也不是
还是非常感谢你的建议
祝学业有成
