### ISSUE TITLE
关于jekyll生成站点地图(sitemap.xml)

### ISSUE THREAD

**Issue by wuxiaoqiang12** [wu-kan/wu-kan.github.io#2]
您好，我想让google收录我的个人网站，在查询jekyll的相关教程后，我在本地安装了jekyll-stemap的插件并且在_config文件中的Plugins中添加了 - jekyll-sitemap,但是运行jekyll s 之后提示我 - jekyll-sitemap这一句缺少冒号，所以我想问下这里正确的写法应该是怎样的？谢谢！

**Comment by wuxiaoqiang12** [comment]
行，谢谢你的回复．我再查查资料看怎么解决这个问题．

wu-kan <notifications@github.com> 于2019年9月11日周三 下午5:05写道：

**Comment by wu-kan** [comment]
当前最新版本已经可以在GitHub上使用jekyll-sitemap了，生成的效果见<https://wu-kan.cn/sitemap.xml>

**Comment by dulunar** [comment]
> 当前最新版本已经可以在GitHub上使用jekyll-sitemap了，生成的效果见https://wu-kan.cn/sitemap.xml

我用的是jekyll 3.8.5，使用sitemap这个一直无法生成，看介绍是3.5以后就没有这个功能了，现在最新版又可以了么？谢谢

**Comment by wu-kan** [comment]
> > 当前最新版本已经可以在GitHub上使用jekyll-sitemap了，生成的效果见https://wu-kan.cn/sitemap.xml
> 
> 我用的是jekyll 3.8.5，使用sitemap这个一直无法生成，看介绍是3.5以后就没有这个功能了，现在最新版又可以了么？谢谢

应该一直就可以吧…可能是你的插件安装有问题。在我的目录下直接 `bundle install` 是可以的 @dulunar
