### ISSUE TITLE
侧边栏的“关于”页面不存在

### ISSUE THREAD

**Issue by Young-Lord** [wu-kan/wu-kan.github.io#20]
RT，点击“关于”会跳转到<https://wu-kan.cn/about/>（404页面）
https://github.com/wu-kan/wu-kan.github.io/blob/f71c46cdcfa5946be116ab7cabe4f911d5fdc374/_config.yml#L165-L166

**Comment by wu-kan** [comment]
本地在开发一个学术主页，大家在用的时候把这个注释掉就行
