### ISSUE TITLE
关于你的激励按钮点击第一次不立即显示？的问题

### ISSUE THREAD

**Issue by XtrueT** [wu-kan/wu-kan.github.io#3]
` document.getElementById('rewardQRs').style.display = document.getElementById('rewardQRs').style.display==="none"?"block":"none";`

**Comment by wu-kan** [comment]
已在本地修复这个问题，解决方法是将`<div id="rewardQRs">`换成`<div id="rewardQRs" style="display: none;">`（把显隐属性从css文件提到内联部分）。

将在国庆之后push上来（最近作业太多了）。

**Comment by wu-kan** [comment]
已经将修复后的代码提交到master，感谢。
