### ISSUE TITLE
关于post.html中的背景音乐代码段使用方法

### ISSUE THREAD

**Issue by Yecgaa1** [wu-kan/wu-kan.github.io#6]
您好
我在查看post.html(html小白，翻文件时)发现了
   ``` 
{% if page.background_music %}
    <div>
      {{ page.background_music }}
    </div>
    {% endif %}
```
我想添加背景音乐，请问该如何使用它，谢谢

**Comment by wu-kan** [comment]
参见<https://github.com/wu-kan/wu-kan.github.io/blob/master/_posts/2020-01-24-%E4%BB%8A%E6%97%A5%E6%AD%A4%E6%97%B6%E6%89%80%E6%83%B3%E4%B9%8B%E4%BA%8B.md>，对应效果见<https://wu-kan.github.io/posts/%E4%BB%8A%E6%97%A5%E6%AD%A4%E6%97%B6%E6%89%80%E6%83%B3%E4%B9%8B%E4%BA%8B>

**Comment by Yecgaa1** [comment]
非常感谢
